version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-yugxgoogle
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file: .env

  redis:
    image: redis:latest
    container_name: redis-yugxgoogle-app
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    env_file : .env

volumes:
  postgres-data:
  redis-data:
