version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-yugxgoogle-app
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file: .env

volumes:
  postgres-data:
